name: Combined generate test and publish

on: [push, pull_request]

jobs:
  CombinedGenerateAndSmoketest:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4
      
      - name: Env echo - Pre
        run: |
            # Default WD:
            pwd
            ls -la
            # Home directory:
            echo "HOME = $HOME"
            ls -la ~
      
      - name: Login on DockerHub via token
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Generate images
        run: |
            for dori in debian12 debian11 debian10 ubuntu22.04
            do  pushd $dori
                docker build -t joaojeronimopro/simplesystems:$dori .
                popd
            done
            for dori in debian12-dpkg debian11-dpkg debian10-dpkg ubuntu22.04-dpkg
            do  pushd $dori
                docker build -t joaojeronimopro/buildsystems:$dori .
                popd
            done
      
      - name: List every image
        run: docker image list -a
      
      - name: Smoke test the images
        run: |
            for dori in debian12 debian11 debian10 ubuntu22.04
            do  docker run --rm --entrypoint /bin/bash joaojeronimopro/simplesystems:$dori --version
            done
            for dori in debian12-dpkg debian11-dpkg debian10-dpkg ubuntu22.04-dpkg
            do  docker run --rm --entrypoint /bin/bash joaojeronimopro/buildsystems:$dori --version
            done
      
      - name: List every container
        run: docker container ls -a
      
      - name: Publish images in Docker Hub
        run: |
            for dori in debian12 debian11 debian10 ubuntu22.04
            do  docker push joaojeronimopro/simplesystems:$dori
            done
            for dori in debian12-dpkg debian11-dpkg debian10-dpkg ubuntu22.04-dpkg
            do  docker push joaojeronimopro/buildsystems:$dori
            done
