name: Combined generate test and publish

on: [push, pull_request]

jobs:
  CombinedGenerateAndSmoketest:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Login on DockerHub via token
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Generate debian12
        run: ./BuildAndTest.bash simplesystems debian12
      - name: Generate debian11
        run: ./BuildAndTest.bash simplesystems debian11
      - name: Generate ubuntu22.04
        run: ./BuildAndTest.bash simplesystems ubuntu22.04
      - name: Generate ubuntu18.04
        run: ./BuildAndTest.bash simplesystems ubuntu18.04

      - name: Generate debian12-dpkg
        run: ./BuildAndTest.bash buildsystems debian12-dpkg
      - name: Generate debian11-dpkg
        run: ./BuildAndTest.bash buildsystems debian11-dpkg
      - name: Generate ubuntu22.04-dpkg
        run: ./BuildAndTest.bash buildsystems ubuntu22.04-dpkg
      
      - name: Publish images in Docker Hub
        run: |
            docker push joaojeronimopro/simplesystems:debian12
            docker push joaojeronimopro/simplesystems:debian11
            docker push joaojeronimopro/simplesystems:ubuntu22.04
            docker push joaojeronimopro/simplesystems:ubuntu18.04
            docker push joaojeronimopro/buildsystems:debian12-dpkg
            docker push joaojeronimopro/buildsystems:debian11-dpkg
            docker push joaojeronimopro/buildsystems:ubuntu22.04-dpkg
